import type { AskIdaraDict } from "./AskIdara";
import type { DockDict } from "./IdaraDock";

/** The dock dictionary, resolved once on the server from the catalog. */
export function dictFor(t: (k: string) => string): DockDict {
  return {
    launcher: t("idara.dock.launcher"),
    open: t("idara.dock.open"),
    close: t("idara.dock.close"),
    minimise: t("idara.dock.minimise"),
    workspace: t("idara.dock.workspace"),
    position: t("idara.dock.position"),
    positions: {
      "top-start": t("idara.dock.pos.top_start"),
      "top-end": t("idara.dock.pos.top_end"),
      "middle-start": t("idara.dock.pos.middle_start"),
      "middle-end": t("idara.dock.pos.middle_end"),
      "bottom-start": t("idara.dock.pos.bottom_start"),
      "bottom-end": t("idara.dock.pos.bottom_end"),
    },
    reset: t("idara.dock.reset"),
    quickAsk: t("idara.dock.quick_ask"),
    placeholder: t("idara.dock.placeholder"),
    send: t("idara.dock.send"),
    thinking: t("idara.dock.thinking"),
    waiting: t("idara.dock.waiting"),
    done: t("idara.dock.done"),
    failed: t("idara.dock.failed"),
    idle: t("idara.dock.idle"),
    unavailable: t("idara.dock.unavailable"),
    evidenceOnly: t("idara.dock.evidence_only"),
    includePage: t("idara.dock.include_page"),
    contextTitle: t("idara.dock.context"),
    remove: t("idara.dock.remove"),
    addRecord: t("idara.dock.add_record"),
    searchPlaceholder: t("idara.dock.search_placeholder"),
    nothingFound: t("idara.dock.nothing_found"),
    agent: t("idara.dock.agent"),
    answeredBy: t("idara.dock.answered_by"),
    contributors: t("idara.dock.contributors"),
    steps: t("idara.dock.steps"),
    evidence: t("idara.dock.evidence"),
    facts: t("idara.dock.facts"),
    calculations: t("idara.dock.calculations"),
    assumptions: t("idara.dock.assumptions"),
    gaps: t("idara.dock.gaps"),
    actions: t("idara.dock.actions"),
    confirm: t("idara.dock.confirm"),
    execute: t("idara.dock.execute"),
    cancelAction: t("idara.dock.cancel_action"),
    stop: t("idara.dock.stop"),
    newConversation: t("idara.dock.new_conversation"),
    conversations: t("idara.dock.conversations"),
    notGenerated: t("idara.dock.not_generated"),
    ownerAction: t("idara.dock.owner_action"),
    credits: t("idara.dock.credits"),
    riskClass: {
      1: t("idara.risk.read"),
      2: t("idara.risk.draft"),
      3: t("idara.risk.reversible"),
      4: t("idara.risk.material"),
      5: t("idara.risk.restricted"),
    },
    status: {
      proposed: t("idara.action_status.proposed"),
      confirmed: t("idara.action_status.confirmed"),
      awaiting_approval: t("idara.action_status.awaiting_approval"),
      approved: t("idara.action_status.approved"),
      executing: t("idara.action_status.executing"),
      executed: t("idara.action_status.executed"),
      failed: t("idara.action_status.failed"),
      refused_drift: t("idara.action_status.refused_drift"),
      cancelled: t("idara.action_status.cancelled"),
      expired: t("idara.action_status.expired"),
      rejected: t("idara.action_status.rejected"),
    },
    shortcutHint: t("idara.dock.shortcut_hint"),
    sizeSmall: t("idara.dock.size_small"),
    sizeMedium: t("idara.dock.size_medium"),
    sizeLarge: t("idara.dock.size_large"),
    moveHint: t("idara.dock.move_hint"),
  };
}

/** Copy for the contextual entry points on record pages. */
export function askDictFor(t: (k: string) => string): AskIdaraDict {
  return {
    button: t("idara.ask.button"),
    about: t("idara.ask.about"),
    explain: t("idara.ask.explain"),
    summarise: t("idara.ask.summarise"),
    compare: t("idara.ask.compare"),
    risks: t("idara.ask.risks"),
    draft: t("idara.ask.draft"),
    next: t("idara.ask.next"),
    automation: t("idara.ask.automation"),
  };
}
