import type { getT } from "@/platform/i18n/server";
import type { BuilderDict } from "./Builder";

type Translator = Awaited<ReturnType<typeof getT>>;

/** The builder copy, shared by the document workspace and the template editor. */
export function builderDict(t: Translator): BuilderDict {
  const k = (key: string) => t(`docstudio.ws.${key}`);
  return {
    insert: k("insert"),
    inspector: k("inspector"),
    nothingSelected: k("nothing_selected"),
    textEn: k("text_en"),
    textAr: k("text_ar"),
    titleEn: k("title_en"),
    titleAr: k("title_ar"),
    level: k("level"),
    listStyle: k("list_style"),
    bullet: k("bullet"),
    numbered: k("numbered"),
    items: k("items"),
    addItem: k("add_item"),
    columns: k("columns"),
    rows: k("rows"),
    addRow: k("add_row"),
    addColumn: k("add_column"),
    removeRow: k("remove_row"),
    source: k("source"),
    manual: k("manual"),
    currency: k("currency"),
    description: k("description"),
    qty: k("qty"),
    unit: k("unit"),
    unitPrice: k("unit_price"),
    vat: k("vat"),
    showVat: k("show_vat"),
    showTotals: k("show_totals"),
    fieldKey: k("field_key"),
    fieldKind: k("field_kind"),
    label: k("label"),
    required: k("required"),
    options: k("options"),
    computed: k("computed"),
    filledBy: k("filled_by"),
    author: k("author"),
    party: k("party"),
    bindingPath: k("binding_path"),
    format: k("format"),
    parts: k("parts"),
    tone: k("tone"),
    info: k("info"),
    warning: k("warning"),
    widthPct: k("width_pct"),
    align: k("align"),
    condition: k("condition"),
    conditionNone: k("condition_none"),
    conditionKey: k("condition_key"),
    conditionOp: k("condition_op"),
    conditionValue: k("condition_value"),
    moveUp: k("move_up"),
    moveDown: k("move_down"),
    duplicate: k("duplicate"),
    remove: k("remove"),
    undo: k("undo"),
    redo: k("redo"),
    saveNow: k("save_now"),
    saving: k("saving"),
    savedAt: k("saved_at"),
    unsaved: k("unsaved"),
    readOnly: k("read_only"),
    fill: k("fill"),
    fillHint: k("fill_hint"),
    settings: k("settings"),
    showLogo: k("show_logo"),
    showIssuer: k("show_issuer"),
    showReference: k("show_reference"),
    footerText: k("footer_text"),
    pageNumbers: k("page_numbers"),
    watermark: k("watermark"),
    numberClauses: k("number_clauses"),
    accent: k("accent"),
    dragHint: k("drag_hint"),
    sectionBlocks: k("section_blocks"),
    empty: k("builder_empty"),
    shortcuts: k("shortcuts"),
    variables: k("variables"),
    kinds: Object.fromEntries(
      ["text", "textarea", "number", "money", "date", "choice", "checkbox", "email", "phone"].map(
        (x) => [x, t(`docstudio.kind.${x}`)],
      ),
    ),
  };
}
