/**
 * The five fictional simulation businesses (micro-step 006A). EVERY value here is
 * invented: no real company, person, TRN, IBAN, bank account, phone number,
 * address or email inbox. Login emails use the RFC-2606 reserved, non-deliverable
 * `example.com` domain and are clearly prefixed `sim-`. Addresses use invented
 * place names. These definitions are committed; the passwords are NOT here — they
 * are generated at provisioning time into a private file outside the repo.
 *
 * Each scenario is matched to a shipped industry template (food_beverage_v1 /
 * service_business_v1 / agriculture_v1); the stage/preset descriptors below mirror
 * that template and are asserted against the installed config at apply time.
 */
import type { Scenario, StageDef, PresetDef } from "./types";

// ── Template config mirrors (kept in sync with src/platform/config/templates) ──

const FB_STAGES: StageDef[] = [
  {
    key: "order_confirmed",
    en: "Order Confirmed & Prep Plan",
    ar: "تأكيد الطلبية وخطة التحضير",
    weight: 10,
  },
  { key: "ingredient_prep", en: "Ingredient Prep", ar: "تجهيز المكونات", weight: 15 },
  { key: "cooking_production", en: "Cooking & Production", ar: "الطبخ والإنتاج", weight: 35 },
  { key: "packing_plating", en: "Packing & Plating", ar: "التعبئة والتقديم", weight: 15 },
  { key: "quality_check", en: "Quality Check", ar: "فحص الجودة", weight: 10 },
  { key: "delivery_service", en: "Delivery & Service", ar: "التوصيل والخدمة", weight: 15 },
];
const FB_PRESETS: PresetDef[] = [
  {
    code: "CAT",
    en: "Catering Order",
    ar: "طلبية تموين",
    skipped: [],
    billing: [
      { trigger: "on_acceptance", pct: 50 },
      { trigger: { stage_key: "delivery_service" }, pct: 50 },
    ],
  },
  {
    code: "PROD",
    en: "Production Batch",
    ar: "دفعة إنتاج",
    skipped: ["delivery_service"],
    billing: [{ trigger: "on_acceptance", pct: 100 }],
  },
  {
    code: "EVNT",
    en: "Event Service",
    ar: "خدمة فعالية",
    skipped: [],
    billing: [
      { trigger: "on_acceptance", pct: 40 },
      { trigger: { stage_key: "delivery_service" }, pct: 60 },
    ],
  },
];

const SVC_STAGES: StageDef[] = [
  { key: "request_logged", en: "Request Logged", ar: "تسجيل الطلب", weight: 5 },
  { key: "scheduled", en: "Scheduled", ar: "تحديد الموعد", weight: 10 },
  { key: "on_site_service", en: "On Site / In Service", ar: "التنفيذ في الموقع", weight: 45 },
  { key: "wrap_up", en: "Wrap-up & Site Cleanup", ar: "الإنهاء وترتيب الموقع", weight: 15 },
  { key: "quality_check", en: "Quality Check", ar: "فحص الجودة", weight: 10 },
  { key: "handover_closed", en: "Handover & Close", ar: "التسليم والإغلاق", weight: 15 },
];
const SVC_PRESETS: PresetDef[] = [
  {
    code: "SVC",
    en: "Service Call",
    ar: "بلاغ خدمة",
    skipped: ["wrap_up"],
    billing: [{ trigger: "on_acceptance", pct: 100 }],
  },
  {
    code: "MNT",
    en: "Maintenance Contract Visit",
    ar: "زيارة عقد صيانة",
    skipped: ["wrap_up"],
    billing: [{ trigger: "on_acceptance", pct: 100 }],
  },
  {
    code: "INST",
    en: "Installation Project",
    ar: "مشروع تركيب",
    skipped: [],
    billing: [
      { trigger: "on_acceptance", pct: 50 },
      { trigger: { stage_key: "handover_closed" }, pct: 50 },
    ],
  },
  {
    code: "OVHL",
    en: "Deep Clean / Major Overhaul",
    ar: "تنظيف عميق / صيانة شاملة",
    skipped: [],
    billing: [
      { trigger: "on_acceptance", pct: 50 },
      { trigger: { stage_key: "handover_closed" }, pct: 50 },
    ],
  },
];

const AG_STAGES: StageDef[] = [
  { key: "land_housing_prep", en: "Land & Housing Prep", ar: "تجهيز الأرض والحظائر", weight: 12 },
  { key: "planting_stocking", en: "Planting / Stocking", ar: "الزراعة / الإدخال", weight: 18 },
  { key: "growing_care", en: "Growing & Care", ar: "النمو والرعاية", weight: 34 },
  { key: "harvest_collection", en: "Harvest / Collection", ar: "الحصاد / الجمع", weight: 20 },
  {
    key: "post_harvest_storage",
    en: "Post-Harvest & Storage",
    ar: "ما بعد الحصاد والتخزين",
    weight: 10,
  },
  { key: "season_close", en: "Season Close", ar: "إغلاق الموسم", weight: 6 },
];
const AG_PRESETS: PresetDef[] = [
  {
    code: "CROP",
    en: "Crop Season",
    ar: "موسم زراعي",
    skipped: [],
    billing: [{ trigger: "on_acceptance", pct: 100 }],
  },
  {
    code: "FMNT",
    en: "Field Maintenance",
    ar: "صيانة الحقول",
    skipped: ["post_harvest_storage"],
    billing: [{ trigger: "on_acceptance", pct: 100 }],
  },
];

// ── 1. Coffee & catering ──────────────────────────────────────────────────────
const COFFEE: Scenario = {
  key: "coffee_catering",
  templateKey: "food_beverage_v1",
  displayName: "Finjan Coffee Catering",
  legalName: "Finjan Coffee Catering Co. (Simulation)",
  tagline:
    "Corporate coffee catering, office refreshment supply, event coffee bars and wholesale bean & pastry orders.",
  personality:
    "Healthy, fast-moving business with growing demand and one manageable collection concern.",
  country: "AE",
  currency: "AED",
  locale: "en",
  languages: ["en", "ar"],
  docLanguage: "bilingual",
  accentColor: "#a8641e",
  vatRegistered: true,
  ownerName: "Yousef Al-Nuaimi",
  ownerEmailLocal: "sim-finjan-owner",
  contact: {
    phone: "+971 50 000 0101",
    email: "sim-finjan-owner@example.com",
    website: "finjan-catering.example",
    addressEn: "Warehouse 7, Marfaa Logistics Park, Dubai, UAE",
    addressAr: "مستودع 7، مجمع مرفأ اللوجستي، دبي",
    city: "Dubai",
  },
  historyMonths: 4,
  richDays: 75,
  stages: FB_STAGES,
  presets: FB_PRESETS,
  itemCategories: ["beverages", "dairy", "bakery_supplies", "packaging", "dry_goods"],
  quoteSectionKeys: ["menu_package", "beverages_desserts", "staffing_service", "delivery_setup"],
  customers: [
    { name: "Meydan Tower Facilities", contactName: "Rana Habib", segment: "office" },
    { name: "Falcon Aviation HQ", contactName: "Omar Siddiqui", segment: "office" },
    { name: "Dune Ventures Coworking", contactName: "Lena Farouk", segment: "office" },
    { name: "Al Waha Events House", contactName: "Tariq Mansour", segment: "event" },
    { name: "Pearl Bay Weddings", contactName: "Salma Idris", segment: "event" },
    { name: "GreenLeaf Grocers (Wholesale)", contactName: "Bilal Anwar", segment: "wholesale" },
    { name: "The Corner Roastery Cafés", contactName: "Nadia Kamal", segment: "wholesale" },
    { name: "Horizon Tech Summit", contactName: "Faisal Rahman", segment: "event" },
    { name: "Cedar Clinics Group", contactName: "Dima Haddad", segment: "office" },
  ],
  suppliers: [
    { name: "Jabal Green Bean Importers", category: "beans", terms: "Net 30" },
    { name: "Oasis Dairy Distributors", category: "dairy", terms: "Net 15" },
    { name: "PaperCraft Packaging Co.", category: "packaging", terms: "Net 30" },
    { name: "Golden Crust Pastry Kitchen", category: "pastry", terms: "COD" },
    { name: "Emirates Barista Supplies", category: "equipment", terms: "Net 30" },
  ],
  items: [
    {
      sku: "BEAN-ETH",
      name: "Ethiopia Yirgacheffe beans",
      categoryKey: "beverages",
      unit: "kg",
      unitCostMajor: 62,
      sellingPriceMajor: 110,
    },
    {
      sku: "BEAN-COL",
      name: "Colombia Supremo beans",
      categoryKey: "beverages",
      unit: "kg",
      unitCostMajor: 48,
      sellingPriceMajor: 92,
    },
    {
      sku: "BEAN-HOUSE",
      name: "Finjan House Blend beans",
      categoryKey: "beverages",
      unit: "kg",
      unitCostMajor: 40,
      sellingPriceMajor: 80,
    },
    {
      sku: "MILK-FULL",
      name: "Full-cream milk (1L)",
      categoryKey: "dairy",
      unit: "L",
      unitCostMajor: 4,
      sellingPriceMajor: 7,
    },
    {
      sku: "MILK-OAT",
      name: "Barista oat milk (1L)",
      categoryKey: "dairy",
      unit: "L",
      unitCostMajor: 9,
      sellingPriceMajor: 15,
    },
    {
      sku: "CUP-12",
      name: "Ripple cup 12oz + lid",
      categoryKey: "packaging",
      unit: "pc",
      unitCostMajor: 0.7,
      sellingPriceMajor: 1.5,
    },
    {
      sku: "CROIS",
      name: "Butter croissant",
      categoryKey: "bakery_supplies",
      unit: "pc",
      unitCostMajor: 2.5,
      sellingPriceMajor: 6,
    },
    {
      sku: "DATE-CK",
      name: "Date & walnut cake slice",
      categoryKey: "bakery_supplies",
      unit: "pc",
      unitCostMajor: 3,
      sellingPriceMajor: 8,
    },
    {
      sku: "SYRUP-VAN",
      name: "Vanilla syrup (750ml)",
      categoryKey: "dry_goods",
      unit: "bottle",
      unitCostMajor: 14,
      sellingPriceMajor: 26,
    },
  ],
  employees: [
    { name: "Karim Aziz", trade: "Head Barista", salaryMajor: 5200, otRate: 1.25 },
    { name: "Hana Yousuf", trade: "Barista", salaryMajor: 3600, otRate: 1.25 },
    { name: "Mateen Raza", trade: "Catering Driver", salaryMajor: 3200, otRate: 1.5 },
    { name: "Sara Nabil", trade: "Pastry Assistant", salaryMajor: 3400, otRate: 1.25 },
  ],
  workTitles: [
    { en: "Weekly office coffee bar", ar: "ركن قهوة أسبوعي للمكاتب" },
    { en: "Product-launch coffee cart", ar: "عربة قهوة لإطلاق منتج" },
    { en: "Wedding barista station", ar: "محطة باريستا لحفل زفاف" },
    { en: "Wholesale bean supply run", ar: "توريد حبوب بالجملة" },
    { en: "Conference refreshment service", ar: "خدمة ضيافة مؤتمر" },
    { en: "Pastry box production batch", ar: "دفعة إنتاج علب المعجنات" },
  ],
};

// ── 2. Short-term rental operations ───────────────────────────────────────────
const RENTAL: Scenario = {
  key: "shortstay_ops",
  templateKey: "service_business_v1",
  displayName: "Layali Stay Operations",
  legalName: "Layali Hospitality Operations Co. (Simulation)",
  tagline:
    "Holiday-home operations: property onboarding, turnover coordination, cleaning & linen, maintenance and owner billing. Not a booking platform.",
  personality:
    "Mature multi-year operation with stable activity, seasonal patterns and several current coordination decisions.",
  country: "AE",
  currency: "AED",
  locale: "en",
  languages: ["en", "ar"],
  docLanguage: "bilingual",
  accentColor: "#3b4c9a",
  vatRegistered: true,
  ownerName: "Reem Al-Balushi",
  ownerEmailLocal: "sim-layali-owner",
  contact: {
    phone: "+971 50 000 0202",
    email: "sim-layali-owner@example.com",
    website: "layali-stays.example",
    addressEn: "Office 214, Nujoom Business Bay Tower, Dubai, UAE",
    addressAr: "مكتب 214، برج نجوم الخليج التجاري، دبي",
    city: "Dubai",
  },
  historyMonths: 38,
  richDays: 90,
  stages: SVC_STAGES,
  presets: SVC_PRESETS,
  itemCategories: ["consumables", "cleaning_supplies", "spare_parts", "tools_accessories"],
  quoteSectionKeys: ["spare_parts", "consumables"],
  customers: [
    { name: "Marina Heights Owner — Villa 12", contactName: "Khalid Rahman", segment: "owner" },
    { name: "Palm Vista Owner — Apt 908", contactName: "Aisha Noor", segment: "owner" },
    { name: "Downtown Loft Owner — 2204", contactName: "Georges Haddad", segment: "owner" },
    { name: "JBR Beach Owner — Suite 5", contactName: "Priya Menon", segment: "owner" },
    { name: "Hillside Retreat Owner — Unit 3", contactName: "Sami Darwish", segment: "owner" },
    { name: "Creekside Owner — 1710", contactName: "Mona Zayd", segment: "owner" },
    { name: "Emaar Portfolio (6 units)", contactName: "Hassan Ali", segment: "portfolio" },
  ],
  suppliers: [
    { name: "CrispLinen Laundry Services", category: "linen", terms: "Net 15" },
    { name: "SparkleClean Turnover Crew", category: "cleaning", terms: "Net 30" },
    { name: "FixIt Home Maintenance", category: "maintenance", terms: "Net 30" },
    { name: "GuestComfort Amenities Supply", category: "consumables", terms: "Net 30" },
    { name: "CoolAir HVAC Contractors", category: "hvac", terms: "COD" },
  ],
  items: [
    {
      sku: "AMEN-KIT",
      name: "Guest amenity kit",
      categoryKey: "consumables",
      unit: "kit",
      unitCostMajor: 18,
      sellingPriceMajor: 35,
    },
    {
      sku: "LINEN-SET",
      name: "King linen set (rental)",
      categoryKey: "consumables",
      unit: "set",
      unitCostMajor: 22,
      sellingPriceMajor: 40,
    },
    {
      sku: "CLEAN-KIT",
      name: "Turnover cleaning kit",
      categoryKey: "cleaning_supplies",
      unit: "kit",
      unitCostMajor: 12,
      sellingPriceMajor: 25,
    },
    {
      sku: "AC-FILTER",
      name: "Split AC filter",
      categoryKey: "spare_parts",
      unit: "pc",
      unitCostMajor: 30,
      sellingPriceMajor: 55,
    },
    {
      sku: "LOCK-BAT",
      name: "Smart lock battery pack",
      categoryKey: "spare_parts",
      unit: "pc",
      unitCostMajor: 25,
      sellingPriceMajor: 45,
    },
    {
      sku: "TOOL-KIT",
      name: "Maintenance tool kit",
      categoryKey: "tools_accessories",
      unit: "kit",
      unitCostMajor: 80,
      sellingPriceMajor: 130,
    },
  ],
  employees: [
    { name: "Nasser Bilal", trade: "Operations Coordinator", salaryMajor: 6000, otRate: 1.25 },
    { name: "Grace Otieno", trade: "Turnover Supervisor", salaryMajor: 4200, otRate: 1.5 },
    { name: "Rohan Das", trade: "Maintenance Technician", salaryMajor: 3800, otRate: 1.5 },
    { name: "Lucia Santos", trade: "Housekeeper", salaryMajor: 3200, otRate: 1.5 },
    { name: "Emil Haddad", trade: "Guest Experience", salaryMajor: 4000, otRate: 1.25 },
  ],
  workTitles: [
    { en: "New property onboarding", ar: "إدراج وحدة جديدة" },
    { en: "Same-day turnover clean", ar: "تنظيف تجهيز الوحدة" },
    { en: "AC servicing visit", ar: "زيارة صيانة تكييف" },
    { en: "Deep clean & linen refresh", ar: "تنظيف عميق وتجديد المفروشات" },
    { en: "Smart-lock installation", ar: "تركيب قفل ذكي" },
    { en: "Plumbing repair callout", ar: "بلاغ إصلاح سباكة" },
    { en: "Quarterly maintenance visit", ar: "زيارة صيانة ربع سنوية" },
  ],
};

// ── 3. Automotive maintenance workshop ────────────────────────────────────────
const AUTO: Scenario = {
  key: "auto_workshop",
  templateKey: "service_business_v1",
  displayName: "TorqueLine Auto Workshop",
  legalName: "TorqueLine Automotive Services (Simulation)",
  tagline:
    "Vehicle maintenance and repair workshop for individual and fleet customers — inspections, repairs, servicing and overhauls.",
  personality:
    "Busy workshop under operational pressure, with visible blockers, approvals and work-in-progress.",
  country: "AE",
  currency: "AED",
  locale: "en",
  languages: ["en", "ar"],
  docLanguage: "bilingual",
  accentColor: "#b3362b",
  vatRegistered: true,
  ownerName: "Marwan Haddad",
  ownerEmailLocal: "sim-torqueline-owner",
  contact: {
    phone: "+971 50 000 0303",
    email: "sim-torqueline-owner@example.com",
    website: "torqueline-auto.example",
    addressEn: "Plot 44, Sanaia Auto Zone, Sharjah, UAE",
    addressAr: "قطعة 44، منطقة الصناعية للسيارات، الشارقة",
    city: "Sharjah",
  },
  historyMonths: 8,
  richDays: 80,
  stages: SVC_STAGES,
  presets: SVC_PRESETS,
  itemCategories: ["spare_parts", "filters_fluids", "consumables", "tools_accessories"],
  quoteSectionKeys: ["spare_parts", "consumables"],
  customers: [
    {
      name: "Ahmed Zayani (Land Cruiser 2019)",
      contactName: "Ahmed Zayani",
      segment: "individual",
    },
    { name: "Sophia Meyer (BMW X5 2021)", contactName: "Sophia Meyer", segment: "individual" },
    { name: "Rashid Fleet — Delivery Vans", contactName: "Rashid Operations", segment: "fleet" },
    { name: "BlueWave Logistics Fleet", contactName: "Karan Shah", segment: "fleet" },
    {
      name: "Layla Hassan (Nissan Patrol 2018)",
      contactName: "Layla Hassan",
      segment: "individual",
    },
    { name: "Metro Cabs Fleet", contactName: "Fadi Nasr", segment: "fleet" },
    { name: "Daniel Okoro (Ford Ranger 2020)", contactName: "Daniel Okoro", segment: "individual" },
    { name: "Green Valley School Buses", contactName: "Mrs. Farida", segment: "fleet" },
  ],
  suppliers: [
    { name: "GulfParts Distribution", category: "parts", terms: "Net 30" },
    { name: "TyrePro Wholesale", category: "tyres", terms: "Net 15" },
    { name: "LubeMax Oils & Fluids", category: "lubricants", terms: "Net 30" },
    { name: "AutoElectric Rebuilds (Outsourced)", category: "outsourced", terms: "COD" },
    { name: "ShineDetail Consumables", category: "consumables", terms: "Net 15" },
  ],
  items: [
    {
      sku: "OIL-5W30",
      name: "Engine oil 5W-30 (4L)",
      categoryKey: "filters_fluids",
      unit: "pc",
      unitCostMajor: 55,
      sellingPriceMajor: 95,
    },
    {
      sku: "FILT-OIL",
      name: "Oil filter",
      categoryKey: "filters_fluids",
      unit: "pc",
      unitCostMajor: 18,
      sellingPriceMajor: 35,
    },
    {
      sku: "FILT-AIR",
      name: "Air filter",
      categoryKey: "filters_fluids",
      unit: "pc",
      unitCostMajor: 30,
      sellingPriceMajor: 60,
    },
    {
      sku: "BRK-PAD",
      name: "Brake pad set (front)",
      categoryKey: "spare_parts",
      unit: "set",
      unitCostMajor: 120,
      sellingPriceMajor: 240,
    },
    {
      sku: "BAT-70AH",
      name: "Battery 70Ah",
      categoryKey: "spare_parts",
      unit: "pc",
      unitCostMajor: 210,
      sellingPriceMajor: 360,
    },
    {
      sku: "TYRE-17",
      name: "Tyre 235/65 R17",
      categoryKey: "spare_parts",
      unit: "pc",
      unitCostMajor: 260,
      sellingPriceMajor: 420,
    },
    {
      sku: "COOL-4L",
      name: "Coolant (4L)",
      categoryKey: "filters_fluids",
      unit: "pc",
      unitCostMajor: 25,
      sellingPriceMajor: 50,
    },
    {
      sku: "WIPER",
      name: "Wiper blade pair",
      categoryKey: "consumables",
      unit: "set",
      unitCostMajor: 22,
      sellingPriceMajor: 45,
    },
  ],
  employees: [
    { name: "Imran Qureshi", trade: "Master Technician", salaryMajor: 5800, otRate: 1.5 },
    { name: "Peter Mwangi", trade: "Mechanic", salaryMajor: 4000, otRate: 1.5 },
    { name: "Vijay Kumar", trade: "Mechanic", salaryMajor: 3800, otRate: 1.5 },
    { name: "Hussein Ali", trade: "Auto Electrician", salaryMajor: 4400, otRate: 1.5 },
    { name: "Sameer Khan", trade: "Service Advisor", salaryMajor: 4200, otRate: 1.25 },
  ],
  workTitles: [
    { en: "Major service (30k km)", ar: "صيانة كبرى (30 ألف كم)" },
    { en: "Brake system repair", ar: "إصلاح نظام الفرامل" },
    { en: "Battery & electrical fault", ar: "عطل بطارية وكهرباء" },
    { en: "Fleet oil-change batch", ar: "دفعة تغيير زيت للأسطول" },
    { en: "Engine diagnostics & repair", ar: "تشخيص وإصلاح المحرك" },
    { en: "Tyre replacement (x4)", ar: "تبديل إطارات (×4)" },
    { en: "AC gas & compressor service", ar: "صيانة مكيّف وكمبروسر" },
  ],
};

// ── 4. Home cupcake business ──────────────────────────────────────────────────
const CUPCAKE: Scenario = {
  key: "home_cupcakes",
  templateKey: "food_beverage_v1",
  displayName: "Sugar Petal Home Bakes",
  legalName: "Sugar Petal Home Bakes (Simulation)",
  tagline:
    "Home-based custom cupcakes and celebration bakes for birthdays, weddings and corporate gifting.",
  personality:
    "Small founder-led business that feels professional, organized and ready to scale — not an empty miniature ERP.",
  country: "AE",
  currency: "AED",
  locale: "en",
  languages: ["en", "ar"],
  docLanguage: "bilingual",
  accentColor: "#c2497a",
  vatRegistered: false,
  ownerName: "Maya Fernandes",
  ownerEmailLocal: "sim-sugarpetal-owner",
  contact: {
    phone: "+971 50 000 0404",
    email: "sim-sugarpetal-owner@example.com",
    website: "sugarpetal-bakes.example",
    addressEn: "Villa 9, Rawaha Community, Al Ain, UAE",
    addressAr: "فيلا 9، مجمع رواحة، العين",
    city: "Al Ain",
  },
  historyMonths: 3,
  richDays: 60,
  stages: FB_STAGES,
  presets: FB_PRESETS,
  itemCategories: ["bakery_supplies", "dairy", "packaging", "dry_goods"],
  quoteSectionKeys: ["menu_package", "beverages_desserts", "delivery_setup"],
  customers: [
    { name: "Noura's Birthday (Private)", contactName: "Noura Salem", segment: "birthday" },
    { name: "The Khoury Wedding", contactName: "Elias Khoury", segment: "wedding" },
    { name: "BrightMinds Nursery", contactName: "Ms. Hind", segment: "corporate" },
    { name: "Aparna Corporate Gifting", contactName: "Aparna Rao", segment: "corporate" },
    { name: "Little Stars Party Planners", contactName: "Yasmin Adel", segment: "event" },
    { name: "Ahmed & Sara Engagement", contactName: "Sara Nasser", segment: "wedding" },
  ],
  suppliers: [
    { name: "BakeWell Ingredients", category: "ingredients", terms: "COD" },
    { name: "SweetBox Packaging", category: "packaging", terms: "COD" },
    { name: "Cake Decor House", category: "decoration", terms: "COD" },
  ],
  items: [
    {
      sku: "FLOUR",
      name: "Cake flour (1kg)",
      categoryKey: "bakery_supplies",
      unit: "kg",
      unitCostMajor: 6,
      sellingPriceMajor: 0,
    },
    {
      sku: "BUTTER",
      name: "Unsalted butter (500g)",
      categoryKey: "dairy",
      unit: "pc",
      unitCostMajor: 14,
      sellingPriceMajor: 0,
    },
    {
      sku: "FONDANT",
      name: "Fondant (1kg)",
      categoryKey: "bakery_supplies",
      unit: "kg",
      unitCostMajor: 28,
      sellingPriceMajor: 0,
    },
    {
      sku: "BOX-12",
      name: "12-cupcake gift box",
      categoryKey: "packaging",
      unit: "pc",
      unitCostMajor: 4,
      sellingPriceMajor: 0,
    },
    {
      sku: "SPRINKLE",
      name: "Edible decoration set",
      categoryKey: "dry_goods",
      unit: "pack",
      unitCostMajor: 9,
      sellingPriceMajor: 0,
    },
  ],
  employees: [
    { name: "Maya Fernandes", trade: "Founder / Baker", salaryMajor: 0, otRate: 1.25 },
    { name: "Reena Thomas", trade: "Weekend Helper", salaryMajor: 1800, otRate: 1.25 },
  ],
  workTitles: [
    { en: "Birthday cupcake tower (48)", ar: "برج كب كيك لعيد ميلاد (48)" },
    { en: "Wedding dessert table", ar: "طاولة حلويات زفاف" },
    { en: "Corporate branded cupcakes", ar: "كب كيك بشعار الشركة" },
    { en: "Custom fondant celebration cake", ar: "كيكة فوندان مخصصة" },
    { en: "Gift-box production batch", ar: "دفعة إنتاج علب الهدايا" },
  ],
};

// ── 5. Date-fruit & palm farm (Arabic default) ────────────────────────────────
const FARM: Scenario = {
  key: "palm_farm",
  templateKey: "agriculture_v1",
  displayName: "بستان الرُطب للتمور",
  legalName: "مزرعة بستان الرُطب للتمور (محاكاة)",
  tagline: "مزرعة نخيل وتمور: الري والرعاية، أعمال النخيل، الحصاد، التعبئة والبيع بالجملة.",
  personality:
    "Seasonal operation with long-term history, field activity, procurement needs and a clear collections picture.",
  country: "AE",
  currency: "AED",
  locale: "ar",
  languages: ["ar", "en"],
  docLanguage: "ar",
  accentColor: "#2e6b34",
  vatRegistered: true,
  ownerName: "Saif Al-Dhaheri",
  ownerEmailLocal: "sim-rutab-owner",
  contact: {
    phone: "+971 50 000 0505",
    email: "sim-rutab-owner@example.com",
    website: "rutab-grove.example",
    addressEn: "Farm 27, Rimaal Agricultural Belt, Al Ain, UAE",
    addressAr: "مزرعة 27، حزام رمال الزراعي، العين",
    city: "Al Ain",
  },
  historyMonths: 26,
  richDays: 90,
  stages: AG_STAGES,
  presets: AG_PRESETS,
  itemCategories: [
    "fertilisers",
    "pesticides_sprays",
    "irrigation_parts",
    "packaging_crates",
    "tools_spares",
  ],
  quoteSectionKeys: [],
  customers: [
    { name: "أسواق الواحة للتجزئة", contactName: "منصور العلي", segment: "wholesale" },
    { name: "مصنع تمور الخليج", contactName: "خالد الرشيدي", segment: "processor" },
    { name: "تعاونية المزارعين", contactName: "أحمد سالم", segment: "coop" },
    { name: "متاجر البركة للتمور", contactName: "ليلى حمد", segment: "retail" },
    { name: "مصدّر الرُطب الطازج", contactName: "يوسف كرم", segment: "exporter" },
    { name: "فندق الرمال الذهبية", contactName: "نورة سعيد", segment: "hospitality" },
  ],
  suppliers: [
    { name: "مؤسسة أسمدة الواحة", category: "fertiliser", terms: "Net 30" },
    { name: "شركة أنظمة الري الحديثة", category: "irrigation", terms: "Net 30" },
    { name: "مورّد كراتين وتعبئة التمور", category: "packaging", terms: "COD" },
    { name: "معدات ومبيدات المزارع", category: "agrochem", terms: "Net 15" },
  ],
  items: [
    {
      sku: "FERT-NPK",
      name: "سماد NPK (50كجم)",
      categoryKey: "fertilisers",
      unit: "kg",
      unitCostMajor: 120,
      sellingPriceMajor: 0,
    },
    {
      sku: "FERT-ORG",
      name: "سماد عضوي (كيس)",
      categoryKey: "fertilisers",
      unit: "bag",
      unitCostMajor: 40,
      sellingPriceMajor: 0,
    },
    {
      sku: "SPRAY-PEST",
      name: "مبيد نخيل",
      categoryKey: "pesticides_sprays",
      unit: "L",
      unitCostMajor: 60,
      sellingPriceMajor: 0,
    },
    {
      sku: "DRIP-LINE",
      name: "خط ري بالتنقيط (100م)",
      categoryKey: "irrigation_parts",
      unit: "roll",
      unitCostMajor: 85,
      sellingPriceMajor: 0,
    },
    {
      sku: "CRATE-10",
      name: "صندوق تمر 10كجم",
      categoryKey: "packaging_crates",
      unit: "pc",
      unitCostMajor: 6,
      sellingPriceMajor: 0,
    },
    {
      sku: "SAW-PALM",
      name: "منشار تقليم النخيل",
      categoryKey: "tools_spares",
      unit: "pc",
      unitCostMajor: 140,
      sellingPriceMajor: 0,
    },
  ],
  employees: [
    { name: "راشد المهيري", trade: "مشرف المزرعة", salaryMajor: 5000, otRate: 1.25 },
    { name: "عبدالله يوسف", trade: "عامل نخيل", salaryMajor: 2600, otRate: 1.5 },
    { name: "منير حسن", trade: "عامل ري", salaryMajor: 2600, otRate: 1.5 },
    { name: "جمال إدريس", trade: "عامل حصاد", salaryMajor: 2600, otRate: 1.5 },
    { name: "سعيد الكعبي", trade: "عامل تعبئة", salaryMajor: 2800, otRate: 1.5 },
  ],
  workTitles: [
    { en: "Khalas date harvest", ar: "حصاد تمر الخلاص" },
    { en: "Irrigation network overhaul", ar: "تجديد شبكة الري" },
    { en: "Palm pruning & pollination", ar: "تقليم وتلقيح النخيل" },
    { en: "Fertiliser application cycle", ar: "دورة تسميد" },
    { en: "Packing & wholesale dispatch", ar: "تعبئة وإرسال بالجملة" },
    { en: "Pest control spraying", ar: "رش مكافحة الآفات" },
  ],
};

export const SCENARIOS: Scenario[] = [COFFEE, RENTAL, AUTO, CUPCAKE, FARM];

export function scenarioByKey(key: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.key === key);
}
