/**
 * H33 Pilot Lab — render the access document from the companies definition.
 *
 *   npx tsx tooling/pilot-lab/access-report.ts     # writes docs/H33-ACCESS.md
 *
 * The 45 test logins are derived, not typed: every address comes from
 * `personaEmail()`, the same function the launcher signs in with, so this
 * document cannot drift away from the accounts that actually exist.
 *
 * Read-only: no database connection, no environment, no guard needed.
 */
import { writeFileSync } from "node:fs";
import { COMPANIES, personaEmail } from "./companies";

const OUT = "docs/H33-ACCESS.md";

function main(): void {
  const out: string[] = [];
  const p = (line = "") => out.push(line);

  p("# H33 — Pilot Lab access and test users");
  p();
  p("Generated by `npx tsx tooling/pilot-lab/access-report.ts` from");
  p("`tooling/pilot-lab/companies.ts`. Every address below is produced by the");
  p("same function the launcher signs in with, so this list cannot drift from");
  p("the accounts that exist.");
  p();
  p("## How to sign in");
  p();
  p("You will never be given a password, because none was kept. Each account was");
  p("created with 24 random bytes as its password, which were discarded the moment");
  p("the account existed — never stored, printed or transmitted. Signing in mints a");
  p("**one-time** link through the Supabase Admin API, aimed at the app's own");
  p("`/auth/confirm` route, which consumes it exactly once:");
  p();
  p("```bash");
  p("npm run lab:open -- gulfbuild owner");
  p("```");
  p();
  p("The first argument is the company key, the second the persona key — both");
  p("from the tables below. Add `--no-browser` to print the link instead of");
  p("opening it. Run `npm run lab:open` with no arguments to list everything.");
  p();
  p("If a page 404s while the rest of the app works, clear the build cache first");
  p("(`rm -rf .next`) — a stale one makes whole modules look missing.");
  p();
  p("## Why this is safe");
  p();
  p("- **No password is recoverable.** Each account has one, generated as 24");
  p("  random bytes and thrown away unread, so there is nothing to guess, reuse or");
  p("  leak — and nothing to rotate. The one-time link dies on first use and");
  p("  expires in about an hour. A project admin could set a password from the");
  p("  Supabase dashboard; nothing in this repository can.");
  p("- **The addresses cannot receive mail.** `.invalid` is reserved by RFC 2606");
  p("  precisely so it can never resolve. Nothing sent to these accounts can");
  p("  reach a real inbox.");
  p("- **Test project only.** Every lab tool loads `.env.test.local` explicitly");
  p("  and refuses to run against anything that resolves to production. There is");
  p("  no override flag.");
  p("- **Minting a link needs the service-role key**, which lives only in");
  p("  `.env.test.local` on your machine and is not in the repository.");
  p("- **The people are fictional** — invented names, addresses, bank details and");
  p("  tax identifiers throughout. No real person's data is in the lab.");
  p();
  p("## The five companies");
  p();
  p("| Key | Company | Country | Currency | Template | Week | Languages | History |");
  p("| --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const c of COMPANIES)
    p(
      `| \`${c.key}\` | ${c.nameEn} · ${c.nameAr} | ${c.country} | ${c.currency}` +
        ` | \`${c.templateKey}\` | ${c.sixDayWeek ? "6-day" : "5-day"}` +
        ` | ${c.languages.join(", ")} | ${c.history.from} → ${c.history.asOf} |`,
    );
  p();

  for (const c of COMPANIES) {
    p(`## ${c.nameEn} — \`${c.key}\``);
    p();
    p("| Persona | Sign in as | Role | Use it to test |");
    p("| --- | --- | --- | --- |");
    for (const persona of c.personas)
      p(
        `| \`${persona.key}\` | \`${personaEmail(c.key, persona.key)}\` | ${persona.roleKey} | ${persona.describes} |`,
      );
    p();
    p(`Open the owner's view: \`npm run lab:open -- ${c.key} owner\``);
    p();
  }

  p("## Leaving the lab alone");
  p();
  p("Nothing in this document writes business data. `lab:open` mints a sign-in");
  p("token and starts the app; the app itself is the product, so anything you");
  p("change while signed in is a real change to that company's data — which is");
  p("the point. To put a company back the way it was, the whole lab has to be");
  p("rebuilt; there is no undo.");
  p();
  writeFileSync(OUT, out.join("\n"));
  console.log(
    `wrote ${OUT}: ${COMPANIES.length} companies, ${COMPANIES.reduce((n, c) => n + c.personas.length, 0)} logins`,
  );
}

main();
