/**
 * H33 Pilot Lab — the five companies.
 *
 * All names are invented. None is a real company, and no persona is a real
 * person. Every login is under `pilot-lab.invalid`, a reserved domain that
 * cannot receive mail (RFC 2606).
 *
 * Volume profiles are the knobs the families scale from. They were set against
 * the truth map's budget (~150,000 coherent rows across the five companies,
 * ≤ 300 MB total database) with at least one company past the 1,205-row mark on
 * every paginated surface that matters: customers, items, jobs, tasks, leads,
 * activities, invoices, stock movements, journal lines, documents.
 */
import type { Company, Persona, PersonaKey, VolumeProfile } from "./types";
import { EMAIL_DOMAIN } from "./marker";

export const AS_OF = "2026-09-05";

export function personaEmail(company: string, persona: PersonaKey): string {
  return `h33.${company}.${persona}@${EMAIL_DOMAIN}`;
}

/** The nine personas, with role mapping and what each is for. */
function personas(
  names: Record<PersonaKey, [string, string]>,
  locale: "en" | "ar" = "en",
): Persona[] {
  const p = (
    key: PersonaKey,
    roleKey: Persona["roleKey"],
    describes: string,
    loc: "en" | "ar" = locale,
  ): Persona => ({
    key,
    roleKey,
    archetype: roleKey,
    fullName: names[key][0],
    fullNameAr: names[key][1],
    locale: loc,
    describes,
  });
  return [
    p("owner", "owner", "Owner — sees everything, approves the big things"),
    p("admin", "admin", "Administrator — settings, members, branding, workspace"),
    p("manager", "manager", "Operations manager — projects, jobs, planning, approvals"),
    p("finance", "accounts", "Finance — invoices, payments, banking, journals, tax"),
    p("hr", "manager", "HR — people, leave, attendance, payroll (a manager in the HR department)"),
    p(
      "warehouse",
      "procurement",
      "Warehouse / procurement — stock, receipts, purchase orders, suppliers",
    ),
    p(
      "field",
      "foreman",
      "Field worker / technician — daily reports, attendance, issues, on a phone",
      "ar",
    ),
    p(
      "restricted",
      "foreman",
      "Restricted employee — a foreman on one crew, sees only assigned work",
    ),
    p("auditor", "viewer", "Auditor — read-only across the organisation"),
  ];
}

const baseProfile: VolumeProfile = {
  customers: 300,
  suppliers: 150,
  items: 900,
  employees: 40,
  projects: 300,
  jobs: 1500,
  tasksPerJob: [3, 8],
  leads: 600,
  opportunities: 500,
  activitiesPerOpportunity: [3, 8],
  quotes: 800,
  invoices: 1300,
  purchaseOrders: 700,
  stockMovementsTarget: 6000,
  journalEntries: 1500,
  documents: 120,
  studioPlans: 8,
  assets: 120,
  enables: {
    stock: true,
    lots: false,
    serials: false,
    bom: false,
    payroll: true,
    assets: true,
    docstudio: true,
    studio: true,
    revenue: true,
    establishment: false,
  },
};

export const COMPANIES: Company[] = [
  {
    key: "gulfbuild",
    nameEn: "Marjan Gulf Contracting",
    nameAr: "مرجان الخليج للمقاولات",
    legalNameEn: "Marjan Gulf Contracting L.L.C. (fictional)",
    country: "AE",
    currency: "AED",
    timezone: "Asia/Dubai",
    languages: ["en", "ar"],
    templateKey: "construction_v1",
    sixDayWeek: true,
    history: { from: "2023-09-01", asOf: AS_OF },
    brandColor: "#b45309",
    personas: personas({
      owner: ["Khalid Marjan", "خالد مرجان"],
      admin: ["Layla Haddad", "ليلى حداد"],
      manager: ["Omar Suleiman", "عمر سليمان"],
      finance: ["Reem Al Nahdi", "ريم النهدي"],
      hr: ["Fatima Qassim", "فاطمة قاسم"],
      warehouse: ["Bilal Rehman", "بلال رحمن"],
      field: ["Yousef Karam", "يوسف كرم"],
      restricted: ["Sami Tarek", "سامي طارق"],
      auditor: ["Nadia Farouk", "نادية فاروق"],
    }),
    profile: {
      ...baseProfile,
      customers: 260,
      suppliers: 220,
      items: 1400,
      employees: 90,
      projects: 220,
      jobs: 850,
      tasksPerJob: [2, 5],
      leads: 300,
      opportunities: 260,
      quotes: 700,
      invoices: 1400,
      purchaseOrders: 1300,
      stockMovementsTarget: 9000,
      journalEntries: 1800,
      documents: 160,
      studioPlans: 10,
      assets: 260,
      enables: { ...baseProfile.enables, lots: false, serials: true },
    },
  },
  {
    key: "tradeline",
    nameEn: "Sadaf Trading & Distribution",
    nameAr: "صدف للتجارة والتوزيع",
    legalNameEn: "Sadaf Trading & Distribution L.L.C. (fictional)",
    country: "AE",
    currency: "AED",
    timezone: "Asia/Dubai",
    languages: ["en", "ar"],
    templateKey: "generic_operations_v1",
    sixDayWeek: true,
    history: { from: "2023-06-01", asOf: AS_OF },
    brandColor: "#0f766e",
    personas: personas({
      owner: ["Hassan Sadaf", "حسن صدف"],
      admin: ["Mona Aziz", "منى عزيز"],
      manager: ["Tariq Mansour", "طارق منصور"],
      finance: ["Salma Idris", "سلمى إدريس"],
      hr: ["Huda Nasser", "هدى ناصر"],
      warehouse: ["Ravi Menon", "رافي مينون"],
      field: ["Adel Hamdan", "عادل حمدان"],
      restricted: ["Noor Jaber", "نور جابر"],
      auditor: ["Ibrahim Zaki", "إبراهيم زكي"],
    }),
    profile: {
      ...baseProfile,
      customers: 1400,
      suppliers: 420,
      items: 3200,
      employees: 45,
      projects: 90,
      jobs: 650,
      tasksPerJob: [1, 3],
      leads: 1300,
      opportunities: 1250,
      quotes: 1500,
      invoices: 2600,
      purchaseOrders: 1400,
      stockMovementsTarget: 16000,
      journalEntries: 2600,
      documents: 110,
      studioPlans: 6,
      assets: 90,
      enables: { ...baseProfile.enables, lots: true, serials: true },
    },
  },
  {
    key: "saudimfg",
    nameEn: "Nakhla Precision Manufacturing",
    nameAr: "نخلة للصناعات الدقيقة",
    legalNameEn: "Nakhla Precision Manufacturing Co. (fictional)",
    country: "SA",
    currency: "SAR",
    timezone: "Asia/Riyadh",
    languages: ["ar", "en"],
    templateKey: "manufacturing_workshop_v1",
    sixDayWeek: false,
    history: { from: "2023-01-01", asOf: AS_OF },
    brandColor: "#1d4ed8",
    personas: personas(
      {
        owner: ["Abdulaziz Al Nakhla", "عبدالعزيز النخلة"],
        admin: ["Sara Al Harbi", "سارة الحربي"],
        manager: ["Majed Al Otaibi", "ماجد العتيبي"],
        finance: ["Nouf Al Qahtani", "نوف القحطاني"],
        hr: ["Amal Al Shehri", "أمل الشهري"],
        warehouse: ["Faisal Al Dossari", "فيصل الدوسري"],
        field: ["Mohammed Al Ghamdi", "محمد الغامدي"],
        restricted: ["Rakan Al Mutairi", "راكان المطيري"],
        auditor: ["Hessa Al Zahrani", "حصة الزهراني"],
      },
      "ar",
    ),
    profile: {
      ...baseProfile,
      customers: 220,
      suppliers: 260,
      items: 2600,
      employees: 70,
      projects: 130,
      jobs: 650,
      tasksPerJob: [2, 4],
      leads: 200,
      opportunities: 180,
      quotes: 500,
      invoices: 900,
      purchaseOrders: 1100,
      stockMovementsTarget: 14000,
      journalEntries: 1600,
      documents: 90,
      studioPlans: 6,
      assets: 180,
      enables: {
        ...baseProfile.enables,
        lots: true,
        serials: true,
        bom: true,
        establishment: true,
      },
    },
  },
  {
    key: "consult",
    nameEn: "Bayan Advisory Partners",
    nameAr: "بيان للاستشارات",
    legalNameEn: "Bayan Advisory Partners F.Z.E. (fictional)",
    country: "AE",
    currency: "AED",
    timezone: "Asia/Dubai",
    languages: ["en", "ar"],
    templateKey: "service_business_v1",
    sixDayWeek: false,
    history: { from: "2023-03-01", asOf: AS_OF },
    brandColor: "#7c3aed",
    personas: personas({
      owner: ["Dana Bayan", "دانة بيان"],
      admin: ["Karim Shafik", "كريم شفيق"],
      manager: ["Lina Hourani", "لينا حوراني"],
      finance: ["Ziad Makki", "زياد مكي"],
      hr: ["Rania Sabbagh", "رانيا صباغ"],
      warehouse: ["Jamil Odeh", "جميل عودة"],
      field: ["Marwan Kassab", "مروان كساب"],
      restricted: ["Hala Younes", "هالة يونس"],
      auditor: ["Firas Nassar", "فراس نصار"],
    }),
    profile: {
      ...baseProfile,
      customers: 380,
      suppliers: 60,
      items: 220,
      employees: 55,
      projects: 280,
      jobs: 850,
      tasksPerJob: [3, 6],
      leads: 1350,
      opportunities: 1300,
      activitiesPerOpportunity: [6, 14],
      quotes: 1300,
      invoices: 1500,
      purchaseOrders: 120,
      stockMovementsTarget: 400,
      journalEntries: 1700,
      documents: 320,
      studioPlans: 14,
      assets: 60,
      enables: { ...baseProfile.enables, stock: true, lots: false, serials: false },
    },
  },
  {
    key: "facilico",
    nameEn: "Rukn Facilities & Maintenance",
    nameAr: "ركن للمرافق والصيانة",
    legalNameEn: "Rukn Facilities & Maintenance L.L.C. (fictional)",
    country: "AE",
    currency: "AED",
    timezone: "Asia/Dubai",
    languages: ["en", "ar"],
    templateKey: "service_business_v1",
    sixDayWeek: true,
    history: { from: "2023-09-01", asOf: AS_OF },
    brandColor: "#dc2626",
    personas: personas({
      owner: ["Saeed Rukn", "سعيد ركن"],
      admin: ["Aisha Fadel", "عائشة فاضل"],
      manager: ["Nabil Darwish", "نبيل درويش"],
      finance: ["Maha Salloum", "مها سلوم"],
      hr: ["Dina Khoury", "دينا خوري"],
      warehouse: ["Suresh Pillai", "سوريش بيلاي"],
      field: ["Ahmed Sabri", "أحمد صبري"],
      restricted: ["Walid Amer", "وليد عامر"],
      auditor: ["Ghada Rashed", "غادة راشد"],
    }),
    profile: {
      ...baseProfile,
      customers: 700,
      suppliers: 180,
      items: 1600,
      employees: 120,
      projects: 380,
      jobs: 1400,
      tasksPerJob: [1, 3],
      leads: 500,
      opportunities: 420,
      quotes: 1100,
      invoices: 2400,
      purchaseOrders: 900,
      stockMovementsTarget: 9000,
      journalEntries: 2200,
      documents: 140,
      studioPlans: 8,
      assets: 420,
      enables: { ...baseProfile.enables, lots: false, serials: true },
    },
  },
];

export function companyByKey(key: string): Company {
  const c = COMPANIES.find((x) => x.key === key);
  if (!c) throw new Error(`unknown company ${key}`);
  return c;
}
