/**
 * The permission matrix (doc 06) transcribed INDEPENDENTLY of the enforcement
 * encoding (matrix.ts / MATRIX), keyed by ARCHETYPE → the actions it may perform.
 * The matrix-runner cross-checks can()/MATRIX against this table: two independent
 * transcriptions of the same spec must agree, so a typo in either is caught (doc
 * 10 #15). File UPLOAD/READ authorization is class-based (canAccessFileClass,
 * tested by storage-harness) and intentionally not in this archetype grid.
 */
import type { RoleArchetype } from "@/platform/registries";
import type { Action } from "./matrix";

type Grantable = Exclude<RoleArchetype, "worker_reserved_p3">;

export const EXPECTED_MATRIX: Record<Grantable, readonly Action[]> = {
  // Full member management, file lifecycle, ALL config + masters + skeleton (doc 06 row-by-row).
  owner: [
    "members.view",
    "members.invite",
    "members.deactivate",
    "files.void",
    "files.legal_hold",
    "config.view",
    "config.manage",
    "employees.view",
    "employees.manage",
    "employees.terms.manage",
    "employees.hr.manage",
    "customers.view",
    "customers.manage",
    "catalog.view",
    "catalog.manage",
    "jobs.view",
    "jobs.create",
    "jobs.edit",
    "jobs.price.manage",
    "jobs.price.adjust",
    "jobs.progress.override",
    "stages.update",
    "stages.request_complete",
    "stages.reopen",
    "tasks.manage",
    "tasks.update_status",
    "crew.manage",
    "week.view",
    "comments.create",
    "reports.create",
    "reports.review",
    "reports.backfill",
    "issues.raise",
    "issues.resolve",
    "attendance.manage",
    "attendance.view",
    "approvals.decide",
    "mr.create",
    "mr.convert",
    "po.manage",
    "po.view",
    "grn.create",
    "grn.cancel",
  ],
  admin: [
    "members.view",
    "members.invite",
    "members.deactivate",
    "files.void",
    "files.legal_hold",
    "config.view",
    "config.manage",
    "employees.view",
    "employees.manage",
    "employees.terms.manage",
    "employees.hr.manage",
    "customers.view",
    "customers.manage",
    "catalog.view",
    "catalog.manage",
    "jobs.view",
    "jobs.create",
    "jobs.edit",
    "jobs.price.manage",
    "jobs.progress.override",
    "stages.update",
    "stages.request_complete",
    "stages.reopen",
    "tasks.manage",
    "tasks.update_status",
    "crew.manage",
    "week.view",
    "comments.create",
    "reports.create",
    "reports.review",
    "reports.backfill",
    "issues.raise",
    "issues.resolve",
    "attendance.manage",
    "attendance.view",
    "approvals.decide",
    "mr.create",
    "mr.convert",
    "po.manage",
    "po.view",
    "grn.create",
    "grn.cancel",
  ],
  // Manager (doc 08: the Workshop Manager variant): masters M, jobs/reports, NO
  // config, NO salary/HR side-tables, no invite/deactivate/legal-hold.
  manager: [
    "members.view",
    "files.void",
    "employees.view",
    "employees.manage",
    "customers.view",
    "customers.manage",
    "catalog.view",
    "catalog.manage",
    "jobs.view",
    "jobs.create",
    "jobs.edit",
    "jobs.progress.override",
    "stages.update",
    "stages.request_complete",
    "stages.reopen",
    "tasks.manage",
    "tasks.update_status",
    "crew.manage",
    "week.view",
    "comments.create",
    "reports.create",
    "reports.review",
    "issues.raise",
    "issues.resolve",
    "attendance.manage",
    "attendance.view",
    // S4: decide rule-routed approvals; MR + PO manage + GRN create (no convert,
    // no PO approve beyond decide, no grn.cancel — those are procurement/admin).
    "approvals.decide",
    "mr.create",
    "po.manage",
    "po.view",
    "grn.create",
  ],
  // Field seat (doc 06 literal row): assigned jobs (v) + own reports. NO
  // employee/catalog/member/customer/config surfaces — S3's report form gets
  // its scoped lookups with its slice.
  foreman: [
    "jobs.view",
    "stages.request_complete",
    "tasks.update_status",
    "week.view",
    "comments.create",
    "reports.create",
    // "Issues: raise" C (assigned) — the field's fast path to flag a blocker.
    "issues.raise",
    // S4: MR + GRN create on ASSIGNED jobs (server-enforced F-6); never decides
    // approvals, never manages POs, never sees cost/price.
    "mr.create",
    "grn.create",
  ],
  procurement: [
    "members.view",
    "catalog.view",
    "catalog.manage",
    "jobs.view",
    "week.view",
    "comments.create",
    // "Issues: raise" C for procurement (materials problems → tickets).
    "issues.raise",
    // S4: procurement owns the supply chain — raise MRs, CONVERT them to POs,
    // manage POs, receive goods. Does NOT decide approvals.
    "mr.create",
    "mr.convert",
    "po.manage",
    "po.view",
    "grn.create",
  ],
  accounts: [
    "members.view",
    "employees.view",
    "customers.view",
    "catalog.view",
    "jobs.view",
    "week.view",
    "comments.create",
    // "Issues: raise" C + "Attendance: view" V (payroll input, D-6.2 cost-priv
    // holder — but attendance itself is not a cost wall).
    "issues.raise",
    "attendance.view",
    // S4: accounts decide rule-routed approvals (e.g. expense/payment in later
    // slices) and VIEW POs. Cost-privileged, so amounts are visible to them.
    "approvals.decide",
    "po.view",
  ],
  // Viewer (doc 06): jobs v (redacted) + week view + attendance V — other rows −.
  viewer: ["members.view", "jobs.view", "week.view", "attendance.view"],
};
